version: '3'
services:
    mysql56:
      image: mysql:5.6
      restart: unless-stopped
      container_name: mysql56-container
      ports:
          - "127.0.0.1:3356:3306"
      environment:
          MYSQL_ROOT_PASSWORD: rootPassword
      volumes:
          - /var/lib/mysql56-data:/var/lib/mysql